version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: >
      bash -c "python manage.py migrate &&
               daphne -b 0.0.0.0 -p 8000 realtime_code_editor.asgi:application"


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: celery -A realtime_code_editor worker --loglevel=info

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django

volumes:
  redis-data:
