FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-minimal \
    python3-pip \
    gcc \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 --version && gcc --version

WORKDIR /code_file

COPY python_packages.txt /package/python_packages.txt


RUN python3 -m pip install --no-cache-dir -r /package/python_packages.txt

CMD ["bash"]
