services:
  - type: web
    name: django-app
    env: docker
    plan: free  # Change this to 'starter' or higher if needed
    repo: https://github.com/faysalhassantorjo/RCE.git  # Replace with your actual GitHub repo
    dockerfilePath: Dockerfile
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: DOCKER_HOST
        value: unix:///var/run/docker.sock

  - type: redis
    name: redis
    plan: free  # Use a paid plan if you need persistence
    ipAllowList: []  # Allow connections from any service on Render

  # Environment Container (for Code Execution)
  - type: worker
    name: python-environment
    env: docker
    plan: free
    repo: https://github.com/faysalhassantorjo/RCE.git
    dockerfilePath: Dockerfile.environment
    envVars:
      - key: WORKING_DIR
        value: /code_file
