services:
  - type: web
    name: django-app
    env: docker
    plan: free  # Change as per your need (free, starter, standard, etc.)
    repo: https://github.com/your-repo-url  # Change this to your actual GitHub repo
    dockerfilePath: Dockerfile
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: DOCKER_HOST
        value: unix:///var/run/docker.sock
    disk:
      name: staticfiles
      mountPath: /app/staticfiles

  - type: redis
    name: redis
    plan: free  # Use a suitable plan


  # Environment Container (for Code Execution)
  - type: worker
    name: python-environment
    env: docker
    repo: https://github.com/your-repo-url
    dockerfilePath: Dockerfile.environment
    envVars:
      - key: WORKING_DIR
        value: /code_file
    disk:
      name: code-files
      mountPath: /code_file
