services:
  - name: django
    type: web
    env: docker
    repo: https://github.com/faysalhassantorjo/RCE.git
    region: oregon
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: "6379"
      - key: DOCKER_HOST
        value: unix:///var/run/docker.sock
    healthCheckPath: /

  - name: redis
    type: redis
    plan: free
    region: oregon

  - name: celery
    type: worker
    env: docker
    repo: https://github.com/faysalhassantorjo/RCE.git
    region: oregon
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: "6379"
      - key: DOCKER_HOST
        value: unix:///var/run/docker.sock

  - name: ubuntu-env
    type: worker
    env: docker
    repo: https://github.com/faysalhassantorjo/RCE.git
    region: oregon
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile.ubuntu
