services:
  - name: django-app
    type: web
    env: docker
    repo: https://github.com/faysalhassantorjo/RCE.git
    plan: free
    region: oregon
    buildCommand: docker build -t django-app .
    startCommand: daphne -b 0.0.0.0 -p 8000 realtime_code_editor.asgi:application
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: "6379"
      - key: DOCKER_HOST
        value: unix:///var/run/docker.sock
    autoDeploy: true
    disk:
      name: django-storage
      mountPath: /app/staticfiles
      sizeGB: 1

  - name: redis
    type: redis
    plan: free
    region: oregon
    ipAllowList: []

  - name: python-env
    type: background
    env: docker
    repo: https://github.com/faysalhassantorjo/RCE.git
    plan: free
    region: oregon
    buildCommand: docker build -t python-env -f Dockerfile.ubuntu .
    startCommand: bash
    autoDeploy: true
    disk:
      name: code-storage
      mountPath: /code_file
      sizeGB: 1
