databases:
  - name: redis_server
    type: redis
    plan: free  # Choose free or paid plan

services:
  - type: web
    name: django_app
    build:
      dockerfile: Dockerfile  # Path to your Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 realtime_code_editor.asgi:application  # Override CMD
    envVars:
      - key: REDIS_HOST
        fromDatabase:
          name: redis_server
          property: host  # Auto-injected Redis host
      - key: REDIS_PORT
        fromDatabase:
          name: redis_server
          property: port  # Auto-injected Redis port
      # Remove DOCKER_HOST (not supported on Render)
    port: 8000  # Port your app listens on
    dependsOn:
      - redis_server 