# Generated by Django 5.1.2 on 2024-10-13 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_codefile_channel_codefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels_file', to='editor.channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='codefile',
            field=models.ManyToManyField(related_name='channels_file', to='editor.codefile'),
        ),
    ]
