# Generated by Django 5.1.2 on 2024-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_codefile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
