# Generated by Django 5.1.2 on 2024-12-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_userprofile_is_online_userprofile_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='editor.userprofile')),
            ],
        ),
    ]
