# Generated by Django 5.1.2 on 2024-12-31 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_usercontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.userprofile')),
            ],
        ),
    ]
