# Generated by Django 5.1.2 on 2024-12-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_globalchat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalChat',
            new_name='GlobalChatRoom',
        ),
    ]
