# Generated by Django 5.1.2 on 2025-01-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_rename_globalchat_globalchatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='participants',
            field=models.ManyToManyField(to='editor.userprofile'),
        ),
    ]
