# Generated by Django 5.1.2 on 2025-01-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_alter_channel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='programing_language',
            field=models.CharField(choices=[('PYTHON', 'python3.12.3'), ('C', '13.3.0')], default='PYTHON', max_length=255),
        ),
    ]
