# Generated by Django 5.1.2 on 2025-01-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0015_channel_programing_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='has_permission',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_permission', to='editor.userprofile'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='programing_language',
            field=models.CharField(choices=[('PYTHON', 'python3.12.3'), ('C', 'gcc 13.3.0')], default='PYTHON', max_length=255),
        ),
    ]
