# Generated by Django 5.1.6 on 2025-05-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0016_channel_has_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_file', to='editor.userprofile'),
        ),
    ]
