# Generated by Django 5.1.6 on 2025-05-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0018_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='channel',
            name='has_permission',
            field=models.ManyToManyField(blank=True, related_name='task_permission', to='editor.userprofile'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
