# Generated by Django 5.1.6 on 2025-05-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0019_labtest_available_labtest_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
