# Generated by Django 5.1.6 on 2025-06-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0021_attempttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttest',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
