# Generated by Django 5.1.6 on 2025-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0022_attempttest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttest',
            name='char_deltas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempttest',
            name='time_labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
