# Generated by Django 5.1.6 on 2025-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0023_alter_attempttest_char_deltas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
