# Generated by Django 5.1.6 on 2025-06-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0024_attempttest_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='start_at',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
