# Generated by Django 5.1.6 on 2025-06-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0025_labtest_end_at_labtest_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
