# Generated by Django 5.1.6 on 2025-06-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0026_labtest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttest',
            name='attempt_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
