# Generated by Django 5.1.6 on 2025-07-02 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0027_attempttest_attempt_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='programing_language',
            field=models.CharField(choices=[('PYTHON', 'python3.12.3'), ('C', 'gcc 13.3.0'), ('JAVA', 'openjdk 21.0.2')], default='PYTHON', max_length=255),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
