# Generated by Django 5.1.6 on 2025-07-03 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0028_alter_channel_id_alter_channel_programing_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labtest', to='editor.channel'),
        ),
    ]
