# Generated by Django 5.1.6 on 2025-07-10 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0029_alter_labtest_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptPaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('start_line', models.PositiveIntegerField(default=0)),
                ('end_line', models.PositiveIntegerField(default=0)),
                ('attempt_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasted_attempt_test', to='editor.labtest')),
            ],
        ),
    ]
