# Generated by Django 5.1.6 on 2025-07-10 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0030_attemptpaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptpaste',
            name='attempt_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasted_attempt_test', to='editor.attempttest'),
        ),
    ]
