# Generated by Django 5.1.6 on 2025-07-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0031_alter_attemptpaste_attempt_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontainer',
            name='installd_packages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
