# Generated by Django 5.1.6 on 2025-07-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0032_usercontainer_installd_packages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontainer',
            old_name='installd_packages',
            new_name='installed_packages',
        ),
    ]
