# Generated by Django 5.1.6 on 2025-07-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0033_rename_installd_packages_usercontainer_installed_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='raw_question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
