# Generated by Django 5.1.6 on 2025-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0034_labtest_raw_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttest',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
